# Generated by Django 3.2.9 on 2022-02-12 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thecode', '0005_message_conversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='mostrecentmessage',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mostrecentmessage', to='thecode.message'),
        ),
    ]
